name: Deploy Worker

on:
  repository_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "latest"
        cache: "npm"

    - name: Install modules
      run: npm install wrangler@latest

    - name: Build
      run: npx wrangler build
      
    - name: Install wrangler
      run: npm install -g wrangler@latest  # Installs wrangler globally

    - name: Add Header
      run: |
        cp ${{ github.workspace }}/dist/worker.js ${{ github.workspace }}/dist/worker-original.js
        echo -e "/*!
        * v2ray Subscription Worker (${{ github.sha }})
        * Copyright 2024 Vahid Farid (https://twitter.com/vahidfarid)
        * Licensed under GPLv3 (https://${{ env.GPL_LICENSE_URL }})  # Use environment variable
        * */
        
        $(cat ${{ github.workspace }}/dist/worker.js)" > ${{ github.workspace }}/dist/worker.js

    - name: Deploy (using secrets)
      run: |  # Reference secrets securely
        sed -i "s/KV_NAME/${{ secrets.KV_NAME }}/g" wrangler.toml
        wrangler publish --api-token ${{ secrets.CF_API_TOKEN }} --account-id ${{ secrets.CF_ACCOUNT_ID }}

      env:
        GPL_LICENSE_URL: https://github.com/vfarid/v2ray-worker/blob/main/Licence.md  # Constant for license URL
